AllCops:

  DisplayCopNames: true

  DisplayStyleGuide: true

  Include:
    - '**/Rakefile'


Lint/Eval:
  Enabled: false


Metrics/LineLength:
  Max: 100


Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Documentation:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
