AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - "**/Rakefile"
  SuggestExtensions: false

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

# Security/Eval is enabled globally. Specific eval usage in test step definitions
# is documented with inline rubocop:disable comments explaining the justification.

Style/Documentation:
  Exclude:
    - "features/support/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
