AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "vendor/**/*"
  SuggestExtensions: false

Layout/LineLength:
  Max: 100

Security/Eval:
  Enabled: false

Style/Documentation:
  Exclude:
    - "features/support/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
